# trying bioc2u oriented container, added pandoc-citeproc
# important element is REL_3_20_ISO in ref below
#
# this assumes that a source package in github has the unlikely
# branch name REL_3_20_ISO, and it includes this workflow
#
# focus is on RELEASE_3_20 so that r2u/bioc2u binaries are available
#
# As of 10am 12 feb 2025 the associated Dockerfile is
# FROM rocker/r2u
# 
# RUN apt update
# RUN apt install -y texinfo git vim qpdf
# RUN apt install -y libcurl4-openssl-dev
# # for rcmdcheck via curl
# RUN apt install -y zlib1g-dev
# # for qpdf
# RUN apt install -y libssl-dev
# # for httr -> UCSC.utils -> GenomeInfoDb -> GRanges -> SE
# RUN apt install -y libxml2-dev libpng-dev liblzma-dev libbz2-dev
# # for tximeta, Rhtslib, XML, etc.
# # might as well install pandoc and avoid doing it in action?
# RUN apt install -y pandoc
# 
# RUN Rscript -e "install.packages(c('BiocManager', 'BiocCheck', 'BiocStyle', 'knitr', 'rmarkdown', 'rcmdcheck', 'tinytex', 'qpdf'), update=TRUE, ask=FALSE)"
# RUN Rscript -e "library(tinytex); tinytex::install_tinytex(); tinytex::tlmgr_install('courier')"
# ENV PATH="$PATH:/root/.TinyTeX/bin/x86_64-linux"

name: CI4bioc320
on:
  push:
    branches: [ REL_3_20_ISO ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: vjcitn/jisochk:0.0.1
# using bioc2u in 0.0.1
      env:
        NODE_ENV: development
      options: --cpus 2
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Assess R version
        run: (Rscript -e version)
      - name: show path to R
        run: (which R)
      - name: Where am I
        run: (pwd)
      - name: Checkout Repository 
        uses: actions/checkout@v4 
        with:
          ref: REL_3_20_ISO
      - name: What is here
        run: (ls)
      - name: view DESCRIPTION
        run: (cat DESCRIPTION)
      - name: get dependencies based on bioc source code (allowing alternate name in test repo)
        run: (Rscript -e "BiocManager::install(basename(getwd()), ref='RELEASE_3_20', dependencies=c('Depends', 'Imports', 'LinkingTo', 'Suggests'), update=TRUE, Ncpus=2)")
      - name: get more pkgs
        run: (Rscript -e "BiocManager::install(c('tximeta', 'tximportData', 'readr', 'pasilla', 'glmGamPoi'))")
      - name: get more pkgs by source
        run: (Rscript -e "BiocManager::install(c('tximportData', 'airway', 'apeglm', 'ashr', 'vsn', 'pheatmap'), type='source')")
      - name: get even more pkgs by source
        run: (Rscript -e "BiocManager::install(c('pbapply'), type='source')")
      - name: look at pkgs
        run: (Rscript -e 'print(sort(rownames(installed.packages())))')
      - name: do r cmd check
        run: (Rscript -e "rcmdcheck::rcmdcheck()")
